import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import localFont from "next/font/local";
import ScrollProgressBar from "@/components/ScrollProgressBar";

const JuliusSansOne = localFont({
  src: "../public/Fonts/JuliusSansOne-Regular.ttf",
  variable: "--JuliusSansOne",
});

const CalSans = localFont({
  src: "../public/Fonts/CalSans-Regular.ttf",
  variable: "--CalSans",
});
const Boldye = localFont({
  src: "../public/Fonts/Boldye.ttf",
  variable: "--Boldye",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${Boldye.variable} ${JuliusSansOne.variable} ${CalSans.variable} antialiased`}
      >
        <ScrollProgressBar />
        {children}
      </body>
    </html>
  );
}
